### ISSUE TITLE
Initialize Random State

### ISSUE THREAD

**Issue by mbosland** [vi3k6i5/GuidedLDA#5]
When I set a random_state and run my program multiple times, I receive varying results each time the program is run. I'm looking at counts of documents per seeded topic to see the variations.

I think we need to initialize the random_state with random.seed(random_state) in the __init__ function. When I did that locally, results are repeatable. 

Does that make sense or am I missing something?

**Comment by vi3k6i5** [comment]
@mbosland Looking into it.

**Comment by vi3k6i5** [comment]
Issue replicated.

**Comment by vi3k6i5** [comment]
Fix Deployed in version: guidedlda-2.0.0.dev22.tar.gz

**Comment by vi3k6i5** [comment]
@mbosland Thanks for pointing it out. I had missed that part. How are you liking the library ?

**Comment by mbosland** [comment]
The library is fantastic! Insanely handy and the interface works just like I expect.
