### ISSUE TITLE
AttributeError: module 'guidedlda' has no attribute '_guidedlda'

### ISSUE THREAD

**Issue by HrishikeshGadekar** [vi3k6i5/GuidedLDA#64]
I was able to successfully install the library after days of effort on my Windows 10 machine with Python 3.6. However, I'm facing the AttributeError: module 'guidedlda' has no attribute '_guidedlda' which probably pertains to the .c files written in cython.

It would be great if anyone could respond with a fix.

**Comment by Dfogger** [comment]
Hi, I meet the same problem as you. Did you solve this finally?

**Comment by HrishikeshGadekar** [comment]
Yes. Please find my [Stackoverflow query](https://stackoverflow.com/questions/70691744/attributeerror-module-guidedlda-has-no-attribute-guidedlda)  and my own answer to it.

Please share if you still face any issue.
