### ISSUE TITLE
use "pip install guidedlda" and got “Command "python setup.py egg_info" failed with error code in ......”

### ISSUE THREAD

**Issue by tszxyuan** [vi3k6i5/GuidedLDA#8]
Hello, 
My Anaconda's Version  is 5.0.1 and I use Windows 7.
When I input
pip install guidedlda,
I get an error,
Command "python setup.py egg_info" failed with error code in ......
I'm new to python and I don't know how to solve it .
Hope for your help.

**Comment by vi3k6i5** [comment]
Duplicate of https://github.com/vi3k6i5/GuidedLDA/issues/2

@tszxyuan I don't have a windows machine with me. I am unable to replicate this issue :(

**Comment by tszxyuan** [comment]
Ok, thank you all the same.
